# Official documentation at http://goreleaser.com
project_name: kubekey
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/kk/main.go
  binary: kk
  goarch:
    - amd64
    - arm64
  goos:
    - linux
  hooks:
    post:
      - upx "{{ .Path }}"
  ldflags:
    - -X github.com/kubesphere/kubekey/version.version={{.Version}}
    - -X github.com/kubesphere/kubekey/version.gitCommit={{.ShortCommit}}
    - -X github.com/kubesphere/kubekey/version.metadata=unreleased
    - -w
    - -s
dist: bin
archives:
- name_template: "kubekey-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    linux: linux
    amd64: amd64
    arm64: arm64
  files:
    - README.md
    - README_zh-CN.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - file_name_template: "kubekey-v{{ .Version }}-{{.Os}}-{{.Arch}}"
    homepage: https://github.com/kubesphere/kubekey
    description: "KubeKey provides a flexible, rapid and convenient way to install Kubernetes only, both Kubernetes and KubeSphere, and related cloud-native add-ons. It is also an efficient tool to scale and upgrade your cluster."
    maintainer: kubesphere authors
    license: Apache-2.0
    vendor: Kubesphere
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      arm64: arm64
      linux: linux
